### PR TITLE
Add logo to README.md and README-template.md

### PR DESCRIPTION
**Pull request by andeladenaro**

### CODE REVIEW

**Comment by tadly** [comment]
I spent some time playing with the README and before I merge this here a few things I would like changed.

## 1. Include assets in the repo
I took the liberty of creating the assets the way I want them to be added to the repository (I might revise that in the future, not sure yet).
The contents of [this directory](https://drive.google.com/drive/folders/1Q8y5AvJpivD2R70PvrzR9ctV0q57kiNE?usp=sharing) I'd like to be added in a directory called `media` in the root of the project.

## 2. Readme
For the readme I'd like a few changes which would be difficult to explain so here is the top portion the way I want it (for now) :)

Note how I changed the first heading from `dups` to `Overview`.
```
<p align="center">
  <img alt="dups banner" src="https://github.com/linuxwhatelse/dups/blob/master/media/dups-banner.png">
</p>
<p align="center">
  <a href="https://saythanks.io/to/tadly">
    <img alt="Say Thanks" src="https://img.shields.io/badge/say-thanks-e91e63.svg">
  </a>
  <a href="https://ci.appveyor.com/project/tadly/dups/branch/master">
    <img alt="Build status" src="https://ci.appveyor.com/api/projects/status/ia8xtstfs2bkxu8g/branch/master?svg=true">
  </a>
</p>

# Overview
dups is a simple backup utility which uses [rsync](https://rsync.samba.org/)
for the heavy lifting in the background and adds some sugar around it.  
...
```

I think that's all actually :)

**Comment by andeladenaro** [comment]
1. Which folder I should add the contents? I cannot find any folder named media.

2. I think it's bit difficult to change files before we merge it. I try to copy and paste the heading in my forked repo and it will look like this. 
screen shot 2018-09-25 at 6 07 58 pm

**Comment by andeladenaro** [comment]
Ok, now I see. I have made the folder and add the files.

**Comment by tadly** [comment]
We're getting there.

Now either remove the README changes in this PR and make a new one **or** update both README with the changes I told you before.

**Comment by andeladenaro** [comment]
Ok, I've update both README with the changes you told me before.

**Comment by tadly** [comment]
Looking good :)

Thank you very very much for your contribution. I really do appreciate it!

**Pull request merged**
